### ISSUE TITLE
Lack of performance

### ISSUE THREAD

**Issue by Aeliot-Tm** [kalibora/doctrine-type-tinyint#3]
There is no sense to validate data obtained from database. 
https://github.com/kalibora/doctrine-type-tinyint/blob/f3a68c7f6b4aa2652efdbac36a91a774083e7162/src/TinyintType.php#L52

The database guarantees its correctness. It is always null or an integer represented by (cast to) a string.

Moreover there used heavy function `preg_match`. Which is "ok" for data-storing and not well for displaying of a bunch of values.
https://github.com/kalibora/doctrine-type-tinyint/blob/f3a68c7f6b4aa2652efdbac36a91a774083e7162/src/TinyintType.php#L76

Could you revert implementation of the method `convertToDatabaseValue`?

**Comment by kalibora** [comment]
That makes sense.
Apparently I was so preoccupied with getting rid of the PHPStan warning that I went the extra things.

I will revert it.

**Comment by kalibora** [comment]
I have just released a fixed version.

See: https://packagist.org/packages/kalibora/doctrine-type-tinyint#v0.2.1
